jobs:
  build:
    if: github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
      )
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Maven
      run: mvn verify -e -B -V -DdistributionFileName=apache-maven
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Upload built Maven
      uses: actions/upload-artifact@v4
      with:
        name: built-maven
        path: apache-maven/target/
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
  integration-test:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        PR_HEAD_LABEL: ${{ github.event.pull_request.head.label }}
      name: Collect environment context variables
      run: "set +e\nrepo=maven-integration-testing\ntarget_branch=master\ntarget_user=apache\n\
        if [ \"$GITHUB_EVENT_NAME\" == \"pull_request\" ]; then\n  user=${PR_HEAD_LABEL%:*}\n\
        \  branch=${PR_HEAD_LABEL#*:}\nelse\n  user=${GITHUB_REPOSITORY%/*}\n  branch=${GITHUB_REF#refs/heads/}\n\
        fi\nif [ $branch != \"master\" ]; then\n  git ls-remote https://github.com/$user/$repo.git\
        \ | grep \"refs/heads/${branch}$\" > /dev/null\n  if [ $? -eq 0 ]; then\n\
        \    echo \"Found a branch \\\"$branch\\\" in fork \\\"$user/$repo\\\", configuring\
        \ this for the integration tests to be run against.\"\n    target_branch=$branch\n\
        \    target_user=$user\n  else\n    echo \"Could not find fork \\\"$user/$repo\\\
        \" or a branch \\\"$branch\\\" in this fork. Falling back to \\\"$target_branch\\\
        \" in \\\"$target_user/$repo\\\".\"\n  fi\nelse\n  echo \"Integration tests\
        \ will run against $target_user/$repo for master builds.\"\nfi\necho \"REPO_BRANCH=$target_branch\"\
        \ >> $GITHUB_ENV\necho \"REPO_USER=$target_user\" >> $GITHUB_ENV\n"
      shell: bash
    - continue-on-error: true
      name: Checkout maven-integration-testing
      uses: actions/checkout@v4
      with:
        path: maven-integration-testing/
        persist-credentials: false
        ref: ${{ env.REPO_BRANCH }}
        repository: ${{ env.REPO_USER }}/maven-integration-testing
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: maven/
        persist-credentials: false
    - continue-on-error: true
      name: Build Maven
      run: mvn install -e -B -V -DdistributionFileName=apache-maven -DskipTests -f
        maven/pom.xml
    - continue-on-error: true
      name: Running integration tests
      run: mvn install -e -B -V -Prun-its,embedded -DmavenDistro="$GITHUB_WORKSPACE/maven/apache-maven/target/apache-maven-bin.zip"
        -f maven-integration-testing/pom.xml
      shell: bash
    - continue-on-error: true
      if: failure() && matrix.os != 'windows-latest'
      name: Upload artifact on integration testing
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_number }}-integration-test-artifact-${{ matrix.os }}-${{
          matrix.java }}
        path: ./maven-integration-testing/core-it-suite/target/test-classes/
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        - 21
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions: {}
