jobs:
  build:
    if: github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
      )
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn install -e -B -V -DdistributionFileName=apache-maven
    - continue-on-error: true
      env:
        TAR_BALL: apache-maven/target/apache-maven-bin.tar.gz
      name: Extract tarball
      run: "set +e\nif [ -f ${{ env.TAR_BALL }} ]; then\n  temp_dir=$(mktemp -d)\n\
        \  tar -xzf ${{ env.TAR_BALL }} -C \"$temp_dir\" --strip 1\n  maven_bin_dir=$temp_dir/bin\n\
        \  if [ -d $maven_bin_dir ]; then\n    echo \"tar.gz file \\\"${{ env.TAR_BALL\
        \ }}\\\" successfully extracted in temporarily directory \\\"$temp_dir.\\\"\
        \"\n    echo \"TEMP_MAVEN_BIN_DIR=$maven_bin_dir\" >> $GITHUB_ENV\n  else\n\
        \    echo \"$maven_bin_dir does not exist.\"\n    exit 1;\n  fi\nelse\n  echo\
        \ \"${{ env.TAR_BALL }} does not exist.\"\n  exit 1;\nfi\n"
      shell: bash
    - continue-on-error: true
      name: Clean with Maven
      run: mvn clean
    - continue-on-error: true
      name: Build again with Maven SNAPSHOT
      run: 'set +e

        export PATH=${{ env.TEMP_MAVEN_BIN_DIR }}:$PATH

        mvn verify site -e -B -V -DdistributionFileName=apache-maven -Preporting

        '
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        - 21
        os:
        - ubuntu-latest
        - windows-latest
name: Can Maven build itself
on:
  repository_dispatch:
    types: trigger-ga___maven_build_itself.yml
permissions: {}
